### ISSUE TITLE
After full import get an error upon trying to update one of the document types

### ISSUE THREAD

**Issue by dalemccutcheon** [KevinJump/uSync8#283] opened 2021-09-28 11:52 UTC
Hey,

A full import of usync brought through all my doc types/datatypes etc without any major issues however once i try and update an imported document type i get this error

![image](https://user-images.githubusercontent.com/40206347/135081501-23b90bf4-2987-4379-a99f-a585cdcb8f20.png)

Umbraco version 9.0.0.0
uSync version 9.0.1 

I have tried the same edit with a non-imported document type and i can save the document type with no issues.

Cheers
Dale

**Comment by KevinJump** [comment] 2021-09-28 16:34
Hi, 

haven't seen this on 9 - if you can - can you email me (kevin@jumoo.co.uk) your uSync folder ? 

it does seem simiar to an issue on v8 - i have seen which is usally caused by duplicate doctypes in the uSync folders _(so the doctype has been changed, so there is a new file, but for some reason the old file wasn't also checked in to source control, / blanked when the change was made)_ 

Maybe a clean export is the best thing to do ?

**Comment by KevinJump** [comment] 2021-11-17 11:42
I think this is the same as tabs issue we have seen in #313 

it doesn't have to be that you have changed from tabs to groups, some of the alias/name changes inside the umbraco versions can do this, so we have changed code to better cope. 

We have done quite a bit of work around tab/group name clashing, so hopefully the next release 9.0.3 fixes this issue. (ETA 18th Nov 2021)

**Closed as completed by KevinJump** 2021-11-17 11:42 UTC
Labels: v9/9.0.3
