### ISSUE TITLE
uSync can inadvertently create an app.config file which causes a ConfigurationErrorsException

### ISSUE THREAD

**Issue by harry-gordon** [KevinJump/uSync8#369] opened 2022-03-10 12:04 UTC
**Describe the bug**
If you have an entity (e.g. DocumentType) named app, uSync will create an `app.config` file will get used in compilation and cause an .`ConfigurationErrorsException` on start-up.

**To Reproduce**
1. Create a doc type with alias "app"
2. Do a uSync export
3. Restart the application 💥

**Expected behavior**
That uSync names the file something else.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/28703576/157657438-527b5142-4146-4ee4-b5a6-e233fc63c4ad.PNG)

**About your Site (please complete the following information):**
 - Umbraco Version: 9.3.1
 - uSync Version: 9.0.4, 9.2.0
 - Browser: N/A

**Additional context**

More error details:
```
An error occurred while starting the application.
ConfigurationErrorsException: Configuration file C:\Development\reference\umbraco-study-toolkit\HarryGordon.Umbraco.StudyToolkit.Cms\bin\Release\net5.0\HarryGordon.Umbraco.StudyToolkit.Cms.dll.config does not have root <configuration> tag (C:\Development\reference\umbraco-study-toolkit\HarryGordon.Umbraco.StudyToolkit.Cms\bin\Release\net5.0\HarryGordon.Umbraco.StudyToolkit.Cms.dll.config line 2)
System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(bool ignoreLocal)

ConfigurationErrorsException: Configuration system failed to initialize
System.Configuration.ClientConfigurationSystem.EnsureInit(string configKey)

ConfigurationErrorsException: Configuration file C:\Development\reference\umbraco-study-toolkit\HarryGordon.Umbraco.StudyToolkit.Cms\bin\Release\net5.0\HarryGordon.Umbraco.StudyToolkit.Cms.dll.config does not have root <configuration> tag (C:\Development\reference\umbraco-study-toolkit\HarryGordon.Umbraco.StudyToolkit.Cms\bin\Release\net5.0\HarryGordon.Umbraco.StudyToolkit.Cms.dll.config line 2)
System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(bool ignoreLocal)
System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
System.Configuration.ClientConfigurationSystem.EnsureInit(string configKey)
```

**Comment by KevinJump** [comment] 2022-03-10 12:26
Hi,

Unfortunarly i can't reproduce this 😞  - (just did the steps above) .

the error seams to suggest a config file in the bin folder. and uSync shouldn't touch anything over there. the `uSync.config` is in the root of the uSync/v9 folder ? and that shouldn't really be getting read in by the boot process. 

do you have any custom uSync settings (in appsettings.json) and does your project file (..csproj) have anything setup regards the uSync folder (i shouldn't really need anything).

**Comment by harry-gordon** [comment] 2022-03-10 13:51
Hi Kevin, thanks for the quick response! No worries, I suspected this might be a more nuanced problem... so you're right, it is something in the bin folder, it's a uSync config file named `HarryGordon.Umbraco.StudyToolkit.Cms.dll.config`. You're gonna love this...

It's because I have a ContentType called `App` so uSync has created a file called `app.config` 😆. If I rename these configs everything works fine.

Sorry, the version change was a total red herring.

Edit: didn't know app.config files were a thing, [here's the docs for reference](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/?redirectedfrom=MSDN).

**Comment by KevinJump** [comment] 2022-03-10 15:34
Will be fixed in the next release (if we find we are about to save app.config or web.config we add underscores (`__app__.config` and `__web__.config`). 

there is also a setting in the ~current release~ where you can change the file extension from .config .

_correction this will also be in 9.2.1_

e.g to have using write out `.xml` files

```json
"uSync": {
   "Settings": {
       "DefaultExtension" : "xml" 
    }
 }
```


in v10 we are likely to make this the default (would be a breaking change now).

**Closed as completed** 2022-03-10 15:36 UTC
Labels: 9.x NETCORE, v9/9.3.0

**Comment by harry-gordon** [comment] 2022-03-10 16:45
Thanks Kevin, impressed by the speed of your response as always, particularly on what is a pretty edge case!

I noticed there's a [post on our](https://our.umbraco.com/forum/umbraco-9/107618-dotnet-run-issue#comment-336959) about this so I've linked them to this issue.
