### ISSUE TITLE
Can't log in to umbraco 9 beta 1 in debug mode from Visual Studio after installing usync 9 beta

### ISSUE THREAD

**Issue by TwoMoreThings** [KevinJump/uSync8#233] opened 2021-05-07 18:48 UTC
I can run my site from VS2019 and login to umbraco if I run it from VS with Ctrl-F5, but if I try to run in debug mode from VS, just pressing F5, the front end of the website loads up (although much slower) but the back office does not load (or takes so long I gave up). Uninstalling usync does not fix this as there are usync files which are not removed. I can, however, remove usync files manually and then run the project with F5 and login to Umbraco with no problems.

Once I discovered this I reinstalled usync again for confirmation and it happened again.

When the back office not loading the output window  is filling constantly with the error shown here.

hope this is useful.

![usync 9 beta](https://user-images.githubusercontent.com/13945979/117495200-375bef00-af6d-11eb-8bb9-a1c49b2defd2.png)

**Comment by KevinJump** [comment] 2021-05-08 09:31
yes - there is something strange going on - somewhere in Visual studio / Umbraco i think .

Just did a quick experiment where i took almost all of the uSync javascript out of the project and debugged it in visual studio. 

umbraco-backoffice-extensions-js.js which is the file generated by Umbraco containing the js from plugings took. 18.86 seconds to generate 

![image](https://user-images.githubusercontent.com/431231/117534225-65cae000-afe8-11eb-8813-cb5991ae8bf2.png)

In VSCode i ran the project in debug and the same file took. 504ms

![image](https://user-images.githubusercontent.com/431231/117534244-78451980-afe8-11eb-9ead-363b047f0858.png)

I am going to do some more invesitgation, i may have to talk to the core team.

**Comment by KevinJump** [comment] 2021-05-08 10:12
Done some investigation - looks like i can reproduce this outside of uSync code. so have logged an issue with the core.

https://github.com/umbraco/Umbraco-CMS/issues/10252

**Comment by KevinJump** [comment] 2021-05-10 20:47
Hi, as an update i have discovered that checking "Enable just my code" in the visual studio debugger settings - seems to speed up this process significantly 

![image](https://user-images.githubusercontent.com/431231/117722509-10a1f080-b1d9-11eb-8ac3-43218680088f.png)

you may have this setting turned off - because it is how the Umbraco docs tell you to setup when debugging Umbraco sources - https://our.umbraco.com/documentation/reference/Debugging/ but at the moment it does appear to have some sort of detrimental effect on the code that generate the aggregated JS file in Umbraco.

**Comment by MarGraz** [comment] 2021-05-14 16:19
> 
> 
> Hi, as an update i have discovered that checking "Enable just my code" in the visual studio debugger settings - seems to speed up this process significantly
> 
> ![image](https://user-images.githubusercontent.com/431231/117722509-10a1f080-b1d9-11eb-8ac3-43218680088f.png)
> 
> you may have this setting turned off - because it is how the Umbraco docs tell you to setup when debugging Umbraco sources - https://our.umbraco.com/documentation/reference/Debugging/ but at the moment it does appear to have some sort of detrimental effect on the code that generate the aggregated JS file in Umbraco.

**It works for me.**
 
**I came from an Umbraco 8 Visual Studio environment**, and **with "Enable Just My Code" deactivated**, Umbraco 9 takes about 4 minutes to start up, and after the starting up it was impossible in "Settings > uSync" to see the uSync control panel populated.

**Enabling "Just My Core"** improved the performance, and Umbraco 9 starts in 40 seconds, and I could see the uSync control panel.

I would suggest you to link this issue in the [installation reference](https://docs.jumoo.co.uk/uSync/v9/migration/).

Thank you

**Comment by KevinJump** [comment] 2021-07-28 14:36
This issue was largely fixed within smidge, and how it generates the js files.

**Closed as completed by KevinJump** 2021-07-28 14:36 UTC
