### ISSUE TITLE
Lock request time out errors

### ISSUE THREAD

**Issue by sekmenhuseyin** [KevinJump/uSync8#570] opened 2023-12-04 10:57 UTC
**Describe the bug**
When we are tryin to sync a very large website in umbraco v10.7 and usync v10.7 we get errors and can not sync whole site at once
we think this is related to this umbraco bug: https://github.com/umbraco/Umbraco-CMS/issues/14195

**Additional context**

![image](https://github.com/KevinJump/uSync/assets/1363876/5dcf5c39-8469-4ddd-8a55-95235342dd80)

```
Microsoft.Data.SqlClient.SqlException:
   at Microsoft.Data.SqlClient.SqlConnection.OnError (Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning (Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.TdsParser.TryRun (Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader (Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds (Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader (Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery (Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery (Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction (Umbraco.Infrastructure, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null)
   at NPoco.Database.ExecuteNonQueryHelper (NPoco, Version=5.3.2.0, Culture=neutral, PublicKeyToken=null)
   at NPoco.Database.Execute (NPoco, Version=5.3.2.0, Culture=neutral, PublicKeyToken=null)
```

**Comment by KevinJump** [comment] 2023-12-04 15:00
Hi, 

I Hadn't really seen the other issue, but i have seen the odd lock (which might be the same thing) in other Umbraco reports, uSync might be more a symptom then the cause here., during a sync usync doesn't access the database itself in anyway (all calls are made via the Umbraco services, which then call the repos that do the DB work. I suspect when uSync throws a lot of changes rapidly at Umbraco a timing issue is being exposed causing the issue.

That doesn't mean we won't look at this, (and indeed i think we might have indirectly with other issues). its just we might not be looking at finding the solution in uSync .

All hope isn't lost however there is an issue fixed in Umbraco v10.8 (released last week?) that does some work with scopes and might in its own words fix the route cause of this issue - https://github.com/umbraco/Umbraco-CMS/pull/14947

so it might be worth updating to v10.8 because it might fix this 🤞

**Comment by sekmenhuseyin** [comment] 2023-12-04 20:25
Thanks a lot for the info

cc: @aochmann @imranhaidercogworks

**Comment by harry-gordon** [comment] 2024-05-15 20:53
@sekmenhuseyin @KevinJump have you noticed any improvement since those fixes (https://github.com/umbraco/Umbraco-CMS/pull/14947) went in?

**Comment by KevinJump** [comment] 2024-05-15 21:29
Hi Harry, 

we haven't seen any other reports, but i can't talk to the experience of others, big sites can perform differently based on loads of factors such as hosting and other things firing during imports/exports etc. 

I can say on our testing for usync on both v10 and v13 we don't currently see any locks (but again our tests might not reflect everyones realworld setups).

**Comment by sekmenhuseyin** [comment] 2024-05-17 08:02
Hi Harry,
we haven't seen these kind of errors for a few months now. I believe the error is gone completely. Thank you

**Closed as completed** 2024-05-21 08:30 UTC
