### ISSUE TITLE
uSync reports shows Angular template

### ISSUE THREAD

**Issue by deMD** [KevinJump/uSync8#35] opened 2019-07-22 07:48 UTC
**Describe the bug**
When running uSync on Umbraco 8 when looking at the report it shows only angular templates instead of data. This happens on an Umbraco 8 website which had been upgraded from 8.0.0 to 8.1.0. Reinstalling uSync has not resolved the issue. 
![image](https://user-images.githubusercontent.com/22070292/61615138-900dab00-ac65-11e9-8d8d-1c12b263c88b.png)
![image](https://user-images.githubusercontent.com/22070292/61615146-93a13200-ac65-11e9-9232-47683d570bb4.png)

Umbraco 8.1.0
uSync 8.1.0

**Comment by KevinJump** [comment] 2019-07-22 10:22
Hi 

have you tried updating the ClientDependency Version in the config/clientdependency.config file ? it might be some cached javascript between upgrades. 

Kevin

**Comment by deMD** [comment] 2019-07-22 11:12
Not tried that yet, will do.

**Comment by deMD** [comment] 2019-07-22 11:16
Changing the ClientDependency version did not change the issue sadly.

**Comment by ThomasSkyldahl** [comment] 2019-09-18 11:19
Hi Kevin, I stumpled upon the same issue, its caused by changes to the default JSON Serializer, seems like uSync uses the default serializer settings, it would' probably be good to use special JsonSerializerSettings when serializing and Deserializing in uSync to ensure the formatting is correct.

**Comment by KevinJump** [comment] 2019-09-18 11:21
yeah, I suspected so - we do force a few places, we must have missed a few 

https://github.com/KevinJump/uSync8/blob/v8/8.2/uSync8.BackOffice/Models/SyncProgressModels.cs#L9

**Comment by deMD** [comment] 2019-09-18 11:22
Ah that makes sense. I always remove the existing settings and add my own settings to make sure it formats according to our wishes.

For reference here are my settings:
```csharp
GlobalConfiguration.Configuration.Formatters.Add(new JsonMediaTypeFormatter
                {
                    SerializerSettings = new JsonSerializerSettings
                    {
                        ContractResolver = new CamelCasePropertyNamesContractResolver(),
                        ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                        Formatting = Formatting.Indented
                    }
                }); 
```

**Comment by ThomasSkyldahl** [comment] 2019-09-18 11:24
On this one:
https://github.com/KevinJump/uSync8/blob/2bd2aa544dcfc9314384458d76ff21702d2739d3/uSync8.BackOffice/Models/SyncAction.cs#L13

**Comment by ThomasSkyldahl** [comment] 2019-09-18 11:29
Enums should also be decorated as some prefer them as strings by default others as integers.

**Comment by KevinJump** [comment] 2019-09-18 11:29
you have to be careful doing that, as there have been places in the Umbraco Core where the setting has been missed and then that stops to.

**Comment by KevinJump** [comment] 2019-09-18 11:31
it's safer to do it per controller (can't remember exactly but you can mark up formatters by the controller and then you don't risk breaking other things).

but yes we will fix all our classes to ensure they stay as expected for us.

**Comment by ThomasSkyldahl** [comment] 2019-09-18 11:43
thats a good point, we already have our specialized serializer settings registered in the DI as we use them for other stuff than web requests, so its nice to be able to inject our SharedSerializerSettings.

**Comment by KevinJump** [comment] 2019-09-23 17:52
this will be in the next release 8.2.1

**Closed by KevinJump** 2019-09-23 17:52 UTC
